version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped


  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: unless-stopped


  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8010:8010" 
    restart: unless-stopped

  
  huey_worker:
    build: .
    container_name: huey_worker
    command: python manage.py run_huey --workers 5
    depends_on:
      - web
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped



volumes:
  pgdata:
