services:
  - type: web
    name: vornexus-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: vornexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
