# Generated by Django 5.2.3 on 2025-07-02 19:20

import chats.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(default=chats.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.cv')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
        ),
    ]
